In [2]:
import torch
import numpy as np
a=[2,10,2,5]
np.argmax(a)

1

In [3]:
import gym
e=gym.make("HalfCheetah-v2")
o=e.reset()
o,a=e.observation_space.shape,e.action_space.shape
print(o,a)


(17,) (6,)


In [158]:
a=torch.Tensor([[4,5,6],[5,10,3]])
b=torch.Tensor([5,10,8])
c=torch.Tensor([4,5,6])
d=torch.Tensor([4,15,16])
k=[]
torch.cat(k,out=b)
torch.cat(k,out=c)
print(torch.mean(a,axis=-1))
print(torch.max(b,c))
t=torch.sum(torch.stack([b,c,b],dim=-1),-1)
print(t)
torch.subtract(b,c)
torch.exp(b)
m=torch.stack([b,c,d,c])  #batch=256-->4, dim=17-->3  pred=2
n=torch.stack([c,c,d,c])
print(m.shape,torch.stack([m,n]).shape,torch.mean(torch.stack([m,n]),0).shape)
print(torch.mean(torch.mean(torch.stack([m,n]),-1),0))
print(torch.mean(torch.mean(torch.stack([m,n]),0),-1))
#tensor([ 5.5000,  5.0000, 11.6667,  5.0000])
torch.argmax(b)
torch.min(torch.stack([d,c,b]),0).values.shape
torch.min(d,c)
vec=torch.stack([d,c,b,c])
ind=torch.argmax(vec,0)
#vec.index_select(ind),ind,vec
print(vec.gather(0, ind.view(1,-1)),vec)
print(m.shape)##batch,inp
#batch, nstep, inp

n_steps = 10
train_sequences = np.tile(m[:, None], ( 1,n_steps,  1))
torch.tensor(train_sequences).shape
torch.cat([d,c],dim=1)
#c=torch.Tensor([4,5,6])
#d=torch.Tensor([4,15,16])

tensor([[ 4.,  4.],
        [15.,  5.],
        [16.,  6.]])

In [ ]:
    def quantile_huber_loss_f(quantiles, samples):
        pairwise_delta = samples[:, None, None, :] - quantiles[:, :, :, None]  # batch x nets x quantiles x samples
        abs_pairwise_delta = torch.abs(pairwise_delta)
        huber_loss = torch.where(abs_pairwise_delta > 1,
                                 abs_pairwise_delta - 0.5,
                                 pairwise_delta ** 2 * 0.5)

        n_quantiles = quantiles.shape[2]
        tau = torch.arange(n_quantiles, device=DEVICE).float() / n_quantiles + 1 / 2 / n_quantiles
        loss = (torch.abs(tau[None, None, :, None] - (pairwise_delta < 0).float()) * huber_loss).mean()
        return loss

In [121]:
import torch.nn as nn
no=torch.Tensor([4,-5,6,-3,3,5,-2])  ###nome s
per=torch.Tensor([4.5,-5.8,5.5,-3,3,5,-2])##per
c=torch.Tensor([4,-5,6,0 ,3,0,-2])  

m=nn.Dropout(p=0.2)  #scales other values by 1/(1-p)
c=m(no)###after drped nominal s
c,c==0,(c!=0)*no + (c==0)*per#,torch.randn(10)*0.2

(tensor([ 5.0000, -0.0000,  7.5000, -3.7500,  3.7500,  0.0000, -2.5000]),
 tensor([False,  True, False, False, False,  True, False]),
 tensor([ 4.0000, -5.8000,  6.0000, -3.0000,  3.0000,  5.0000, -2.0000]))

In [175]:
c = torch.tensor([[1., 8., 3.],[-1, 1, 14]])
c+2

tensor([[ 3., 10.,  5.],
        [ 1.,  3., 16.]])

In [132]:
import os
import random
seed=100
os.environ['PYTHONHASHSEED']=str(seed)
np.random.seed(seed)
random.seed(seed)
sigma=np.arange(0,1.2,0.2)
n=[]
update_every=50
update_after=1000
total_steps=int(1e6)
for t in range(total_steps):
    if t >= (update_after) and t % (update_every) == 0:
        for j in range(update_every):
            n.append(np.random.choice(sigma,1)[0])
            

In [154]:
#n.count(0.6000000000000001) #166061-->0, 166085-->0.2,   166255-->0.4   167219-->0.6  166769-->0.8,  166611-->1

n[200000:250000].count(1)


8452

In [144]:
166061 + 166085 + 166255 + 167219 + 166769 +  166611

999000

In [185]:
import gym
e=gym.make("Hopper-v2")
e.observation_space.shape,e.action_space.shape

((11,), (3,))

In [22]:

vec=torch.stack([d,c,b,c,b])  #5-256    5*3
print(vec.shape)
ind=torch.argmax(vec,0)
ca=torch.Tensor([4,5,6,8])
vec=torch.stack([ca,ca*2,ca*3])
vec=torch.stack([vec,vec*2,vec*3,vec*4,vec*5]) #5*3*4
#vec.index_select(ind),ind,vec
indd=ind.view(1,-1)
print(vec.shape,ind,indd.unsqueeze(2))
print(vec,"\n\n\t",vec.gather(0, indd.unsqueeze(1)))
        j=0
        m=[]
        for i in ind:
            m.append(vec[i,j,:])
            j+=1
        torch.stack(m)

IndentationError: unexpected indent (<ipython-input-22-cd90fc3217cc>, line 11)

In [23]:
ind.view(1,-1)

tensor([[2, 0, 0]])

In [24]:
d=torch.Tensor([5,10,3,1,1])
d=torch.stack([d,d,d],dim=1)

logp_a2=torch.Tensor([2,1,2,1,1])
logp_a2=torch.stack([logp_a2,logp_a2,logp_a2],dim=1)

r=torch.Tensor([4,5,6,2,2])
r=torch.stack([r,r,r],dim=1)
q_pi_targ=torch.Tensor([[4,2,2],[0,2,1],[2,2,2],[2,1,2],[1,4,2]])
alpha=1
gamma=1

print("SHApe of q1",r.shape,gamma,d.shape,q_pi_targ.shape,alpha,logp_a2.shape) 
k= (q_pi_targ - alpha * logp_a2)
d

SHApe of q1 torch.Size([5, 3]) 1 torch.Size([5, 3]) torch.Size([5, 3]) 1 torch.Size([5, 3])


tensor([[ 5.,  5.,  5.],
        [10., 10., 10.],
        [ 3.,  3.,  3.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [25]:
import torch.nn as nn

hidden_sizes=[256,256]
sizes=[17 + 6] + list(hidden_sizes) + [1]
layers=[]
for j in range(len(sizes)-1):
    act = nn.ReLU
    layers += [nn.Linear(sizes[j], sizes[j+1]), act()]
outputs = []
quantiles = [.1, .5, .9]
for i, quantile in enumerate(quantiles):
    outputss = nn.Linear(1, 1)
    outputs.append(outputss)
qf1=outputs

In [26]:
import torch.nn as nn

hidden_sizes=[256,256]
sizes=[17 + 6] + list(hidden_sizes) + [1]
layers=[]
for j in range(len(sizes)-1):
    activation = nn.ReLU
    output_activation=nn.Identity
    act = activation if j < len(sizes)-2 else output_activation
    layers += [nn.Linear(sizes[j], sizes[j+1]), act()]


In [130]:
l=nn.Sequential(*layers)
l

Sequential(
  (0): Linear(in_features=23, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=256, bias=True)
  (3): ReLU()
  (4): Linear(in_features=256, out_features=1, bias=True)
  (5): Identity()
)

In [32]:
qf1

[Linear(in_features=1, out_features=1, bias=True),
 Linear(in_features=1, out_features=1, bias=True),
 Linear(in_features=1, out_features=1, bias=True)]

In [102]:
import pickle

In [ ]:
result_dir ="/home/admin12/Downloads/github/pc_snn/pop-spiking-deep-rl/popsan_drl/popsan_sac/result/6quantile_doublerobust_rbdata/params/spike-sac_sac-popsan-Walker2d-v2-encoder-dim-10-decoder-dim-10"
    test_reward, _ = pickle.load(open(result_dir + '/model' + str(m) + '_test_rewards.p', 'rb'))

pickle.load("data0_train.p")

In [111]:
import pandas
result_dir ="/home/admin12/Downloads/github/pc_snn/pop-spiking-deep-rl/popsan_drl/popsan_sac/params/spike-sac_sac-popsan-Walker2d-v2-encoder-dim-10-decoder-dim-10/"

In [121]:
x=pandas.read_csv(result_dir+"data0_traincsv.csv")
x.shape

(30189, 6)

In [123]:
x.iloc[-1]

t                                                 29550
a     [[ 0.92244226  0.7706839  -0.79540044  0.65893...
o2    [ 1.25979971e+00  4.40815960e-03  2.11260941e-...
r                                              0.271442
d                                                 False
_                                                    {}
Name: 30188, dtype: object

In [131]:
import gym
e=gym.make("Walker2d-v2")
o=e.reset()

In [135]:
import torch.nn as nn
a=[4,0.5,0.2,0.4,0.2,0.4]#e.action_space.sample()
a=nn.Identity(a)
print(a)
s,r,d,_=e.step(a)
print(s,r,d,_)

Identity()


TypeError: float() argument must be a string or a number, not 'Identity'

In [219]:
import csv
result_dir ="/home/admin12/Downloads/github/pc_snn/pop-spiking-deep-rl/popsan_drl/popsan_sac/"
fold="result_walk/usable/"
#fold="result_reacher/"
typee="15with2actorseed100"
with open(result_dir+fold+typee+"/terminal","r") as f:
    a=f.read()
t=a.split("Model:")
#t[1]
with open(result_dir +fold+typee+ '/' + "csv_terminal" + str(0) + '_out.csv', 'w', newline='\n') as csvfile:
    fieldnames = ["t",typee+"_Mean_rew"]
    writer3 = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer3.writeheader()
    for tem in t:
        if "Steps" in tem:
            print(t.index(tem))
            k=tem.split("\n")[0].split()
            print(k)
            writer3.writerow({'t':k[2], typee+'_Mean_rew':k[5]})


1
['0', 'Steps:', '10000', 'Mean', 'Reward:', '-8.565531149822563']
2
['0', 'Steps:', '20000', 'Mean', 'Reward:', '-4.482622564579022']
3
['0', 'Steps:', '30000', 'Mean', 'Reward:', '-4.26048292183834']
4
['0', 'Steps:', '40000', 'Mean', 'Reward:', '-3.6485127157151913']
5
['0', 'Steps:', '50000', 'Mean', 'Reward:', '-4.132680813353061']
6
['0', 'Steps:', '60000', 'Mean', 'Reward:', '-2.9099938019507077']
7
['0', 'Steps:', '70000', 'Mean', 'Reward:', '-3.790674727081124']
8
['0', 'Steps:', '80000', 'Mean', 'Reward:', '-3.7305064043709044']
9
['0', 'Steps:', '90000', 'Mean', 'Reward:', '-4.854462689202131']
10
['0', 'Steps:', '100000', 'Mean', 'Reward:', '-3.4668826207614942']
11
['0', 'Steps:', '110000', 'Mean', 'Reward:', '-4.8283307672020905']
12
['0', 'Steps:', '120000', 'Mean', 'Reward:', '-3.536351454238164']
13
['0', 'Steps:', '130000', 'Mean', 'Reward:', '-4.0088272013317905']
14
['0', 'Steps:', '140000', 'Mean', 'Reward:', '-4.284870865336137']
15
['0', 'Steps:', '150000', 'Mea

In [221]:
from PIL import Image
import gym
#import cv2
# org 
org = (50, 200) 
  
# fontScale dd
fontScale = 0.5
   
# Blue color in BGR 
color = (100, 0,40 ) 
  
# Line thickness of 2 px 
thickness = 1
env=gym.make("Reacher-v2")

result_dir ="/home/admin12/Downloads/github/pc_snn/pop-spiking-deep-rl/popsan_drl/popsan_sac/"
for ep in range(1):
    folder_name=result_dir+"result_reacher/"+"episode"+str(ep)
    os.mkdir(folder_name)
    obs = env.reset()
    im=env.render(mode="rgb_array")
    k=0
    i=0
    ret=0
    while True:
        ac=env.action_space.sample()
        im=Image.fromarray(np.array(im))
        im.save(folder_name+"/"+str(k)+".png")
        k+=1
        #img=cv2.imread(folder_name+"/"+str(k)+".png")
        obs, rewards, dones, info = env.step(ac)
        im=env.render( mode="rgb_array")
        ret += rewards
        i+=1
        if dones:
            print("#############",ret)
            #cv2.imwrite(folder_name+"/"+str(k)+".png", im)
            obs = env.reset() 
            break

############# -40.712070642793655
